### ISSUE TITLE
Remove pulley menu for card grading

### ISSUE THREAD

**Issue by jansol** [prplmnky/harbour-nemosyne#21]
Pulley menus with more than 3 items are generally a bad idea and become difficult to use. So instead of the pulley menu for grading cards I propose using hot areas/sliders: divide the screen into segments marked 0-5 and grade the card by pushing the card away along the corresponding segment. This would make the app more pleasant to use and be more consistent with switching between the sides of a card (all gestures while reviewing are horizontal swipes).

Maybe even have multiple page indicators on the right hand side? Page indicators with numbers on or next to them could be used to mark the hot areas.

**Comment by prplmnky** [comment]
Added in v1.2.3
Will close once accepted by Harbour
